concommand.Add( "hunt_WitchingHour", function()
	RunConsoleCommand("stormfox2_setweather", "rain","0.15")
	RunConsoleCommand("stormfox2_setthunder","1")
	RunConsoleCommand("stormfox2_settime","1815")
end)